# Generated by Django 4.0 on 2025-04-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_column='5CS01_01_G_Session', max_length=100)),
                ('emotion', models.CharField(db_column='5CS01_01_G_Vote', max_length=100)),
                ('team', models.CharField(db_column='5CS01_01_G_Team', max_length=100)),
            ],
        ),
    ]
